language: java
jdk:
  - oraclejdk9
notifications:
  email:
    on_success: never
    on_failure: always
sudo: false
addons:
  apt:
    packages:
      - oracle-java9-installer
      - oracle-java9-set-default
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
build:
  - mvn clean package
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r target/site/jacoco/jacoco.xml
